//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCApp01.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDD_DIALOGBAR                   103
#define IDD_PROPPAGE_MEDIUM             106
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MFCApp01TYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_EDIT01                  310
#define IDD_DLG_LIST01                  314
#define IDR_HTML1                       319
#define IDR_TOOLBAR1                    320
#define IDD_COMBOBOX01                  323
#define IDD_DLG_IMAGE                   327
#define IDB_IMAGE_ACUMI                 331
#define IDD_DLG_LISTVIEW01              332
#define IDD_DLG_RADIO01                 335
#define IDC_READ                        1000
#define IDC_EDIT_INPUT                  1002
#define IDC_OUTPUT                      1003
#define IDC_EDIT_OUTPUT                 1004
#define IDC_BTN_OUT_DATA                1005
#define IDC_LIST_SELECT                 1010
#define IDC_GROUP1                      1011
#define IDC_EDIT_SHOW_SELECTED          1012
#define IDC_COMBO1                      1013
#define IDC_EDIT1                       1014
#define IDC_COMBO_BRUSH_COLOR           1014
#define IDC_BUTTON1                     1015
#define IDC_EDIT_VERBAL                 1015
#define IDC_COMBO2                      1016
#define IDC_EDIT_MATH                   1016
#define IDC_COMBO3                      1017
#define IDC_EDIT_ENGLISH                1017
#define IDC_EDIT2                       1018
#define IDC_EDIT3                       1019
#define IDC_MFCBUTTON1                  1020
#define IDC_COMBO_BASE                  1021
#define IDC_COMBO_ADV                   1022
#define IDC_COMBO_OTHER                 1023
#define IDC_EDIT_BASE_INFO              1024
#define IDC_EDIT_ADV_INFO               1025
#define IDC_EDIT_OTHER_INFO             1026
#define IDC_ANIMATE1                    1027
#define IDC_MFCMENUBUTTON1              1028
#define IDC_MFCSHELLTREE1               1032
#define IDC_MFCVSLISTBOX1               1033
#define IDC_MFCMASKEDEDIT1              1034
#define IDC_COMMONDIALOG1               1037
#define IDC_IMAGE                       1038
#define IDC_BTN_LOAD_IMAGE              1039
#define IDC_BTN_CLEAR_IMAGE             1040
#define IDC_LIST_INFO                   1040
#define IDC_RADIO_BOY                   1041
#define IDC_RADIO_GIRL                  1042
#define IDC_BTN_UPDATE_ID               1043
#define IDC_BTN_SELECT_ID               1044
#define IDC_BTN_SHOW_CHART              1045
#define IDC_BTN_ADD_INFO                1046
#define IDC_BTN_DELETE_INFO             1047
#define IDC_BTN_CLEAR_DB                1048
#define IDC_EDIT_ID                     1049
#define IDC_EDIT_NAME                   1050
#define IDC_LIST_SHAPE                  1051
#define IDC_RADIO_LINE_TYPE1            1052
#define IDC_RADIO_LINE_TYPE2            1053
#define IDC_RADIO_LINE_TYPE3            1054
#define IDC_RADIO_LINE_TYPE4            1055
#define IDC_RADIO_FILL_TYPE1            1056
#define IDC_RADIO_FILL_TYPE2            1057
#define IDC_RADIO_FILL_TYPE3            1058
#define IDC_RADIO_FILL_TYPE4            1059
#define IDC_BTN_DRAW                    1060
#define IDC_BTN_CLEAR                   1061
#define IDC_COMBO_PEN_COLOR             1062
#define IDC_STATIC_DRAW                 1063
#define ID_DEMOS_EDITCONTROL            32771
#define ID_BUTTON32772                  32772
#define ID_DEMOS_LISTBOX01              32773
#define ID_DEMOS_COMBOBOX01             32774
#define ID_DEMOS_IMAGEDEMO01            32775
#define ID_DEMOS_RADIODEMO01            32776
#define ID_DEMOS_SCREENCAPTURE01        32777
#define ID_DEMOS_LISTVIEWDEMO01         32778
#define ID_DEMOS_STUDENT_INFO           32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
